config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index" # トップページのルーティング
  
  get "login", to: "sessions#new" # ログインページのURIパターンを"login"にする設定
  post "login", to: "sessions#create" # ログインページのURIパターンを"login"にする設定
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new" # ユーザ登録ページのURLパターンを"signup"にする設定
  resources :users, only: [:index, :show, :create] do
    member do # idが含まれるURLの生成（ユーザの特定が必要）
      get :likes
    end
  end
  
  get "signup", to: "users#new"
  
  resources :cabinets
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cabinet.rb
class Cabinet < ApplicationRecord
  belongs_to :user
  
  with_options presence: true, length: { maximum: 50 } do # カラ禁止、50字以内
    validates :title_cabinet # 内閣の名前
  
    validates :prime_minister_name # 総理大臣
    validates :chief_cabinet_secretary_name # 内閣官房長官
    validates :finance_minister_name # 財務大臣
    validates :comprehensive_minister_name # 総務大臣
    validates :economy_minister_name # 経済産業大臣
    validates :welfare_minister_name # 厚生労働大臣
    validates :education_minister_name # 文部科学大臣
    validates :diplomacy_minister_name # 外務大臣
    validates :defense_minister_name # 防衛大臣
    validates :agriculture_minister_name # 農林水産大臣
    validates :traffic_minister_name # 国土交通大臣
    validates :law_minister_name # 法務大臣
    validates :green_minister_name # 環境大臣
    validates :digital_minister_name # デジタル大臣
    validates :reconstruction_minister_name # 復興大臣
    validates :public_security_minister_name # 国家公安委員長
  end
  
  has_many :favorites, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :cabinet, class_name: "Cabinet"
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! } # 文字を全て、小文字から大文字に変換
  validates :name, presence: true, length: { maximum: 50 } # ユーザの名前は、カラ禁止の50字以内
  validates :email, presence: true, length: { maximum: 255 }, # Eメールは、カラ禁止の255字以内
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false } # Eメールの重複禁止
  has_secure_password
  
  has_many :cabinets
  has_many :favorites
  has_many :likings, through: :favorites, source: :cabinet
  # throughはモデル、sourceはどこから取得するか
  
  def like(other_cabinet) 
    self.favorites.find_or_create_by(cabinet_id: other_cabinet.id) # お気に入りの重複対策
  end
  
  def unlike(other_cabinet) 
    like = self.favorites.find_by(cabinet_id: other_cabinet.id) # お気に入り登録済みならば外す
    like.destroy if like # 中間テーブルからも消す
  end
  
  def liking?(other_cabinet)
    self.likings.include?(other_cabinet) # お気に入り登録しているcabinetを取得し、お気に入りではないcabinetが含まれていないか確認
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  include Pagy::Backend # Bootstrapの呼び出し
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/cabinets_controller.rb
class CabinetsController < ApplicationController
  before_action :require_user_logged_in # ログインしていなければダメ
  before_action :correct_user, only: [:edit, :update, :destroy] # 自分しかダメ
  before_action :cabinet_find, only: [:show]
  
  def index
    @cabinets = current_user.cabinets.order(id: :desc)
  end
  
  def show 
  end
  
  def new
    @cabinet = Cabinet.new
  end

  def create
    @cabinet = current_user.cabinets.build(cabinet_params)
    if @cabinet.save
      flash[:success] = "組閣しました"
      redirect_to cabinets_path
    else
      @pagy, @cabinets = pagy(current_user.cabinets.order(id: :desc))
      flash.now[:danger] = "組閣することができませんでした"
      render :new
    end
  end

  def edit
    @cabinet = Cabinet.find(params[:id])
  end

  def update
    @cabinet = current_user.cabinets.find(params[:id])
    
    if @cabinet.update(cabinet_params)
      flash[:success] = "#{@cabinet.title_cabinet} は更新されました"
      redirect_to @cabinet
    else
      flash.now[:danger] = "内閣の更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @cabinet.destroy
    flash[:success] = "内閣を削除しました"
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def cabinet_params
    params.require(:cabinet).permit(:title_cabinet, :prime_minister_name, :chief_cabinet_secretary_name, :finance_minister_name, :comprehensive_minister_name, :economy_minister_name, :education_minister_name, :welfare_minister_name, :diplomacy_minister_name, :defense_minister_name, :agriculture_minister_name, :traffic_minister_name, :law_minister_name, :green_minister_name, :digital_minister_name, :reconstruction_minister_name, :public_security_minister_name)
  end
  
  def correct_user
    @cabinet = current_user.cabinets.find_by(id: params[:id]) # id:ログイン中ユーザのcabinetsテーブルから
    unless @cabinet
      redirect_to root_path
    end
  end
  
  def cabinet_find
    @cabinet = Cabinet.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in # ログイン中

  def index
    if logged_in?
      @cabinet = current_user.cabinets.build
      @pagy, @cabinets = pagy(current_user.feed_cabinets.order(id: :desc))
    end
  end
  
  def create
    cabinet = Cabinet.find(params[:cabinet_id])
    current_user.like(cabinet) # ログイン中のユーザがcabinetをlikeしました
    flash[:success] = "Cabinetをお気に入り登録しました"
    redirect_to current_user
  end

  def destroy
    cabinet = Cabinet.find(params[:cabinet_id])
    current_user.unlike(cabinet)
    flash[:success] = "Cabinetのお気に入り登録を解除しました"
    redirect_to current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインしました"
      redirect_to root_path
    else
      flash.now[:danger] = "ログインできませんでした"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @cabinets = Cabinet.all
    if logged_in?
      @cabinet = current_user.cabinets.build
      @pagy, @cabinets = pagy(current_user.cabinets.order(id: :desc))
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:edit, :update, :destroy, :likes] # ログインしていなければダメ
  before_action :correct_user, only: [:edit, :update, :destroy] # 自分しかダメ
  
  def show # ユーザの詳細ページのルーティング（今は無いが、将来的には必要になるので書いている。）
    @user = User.find(params[:id])
    @pagy, @cabinets = pagy(@user.cabinets.order(id: :desc))
  end

  def new # ユーザ登録用フォームのルーティング
    @user = User.new
  end

  def create # ユーザ登録の処理
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザーを登録しました"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザーの登録に失敗しました"
      render :new
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy # ユーザを削除する機能（あとはボタンを追加するだけ）
    @user.destroy
    flash[:success] = "アカウントを削除しました"
    redirect_back(fallback_location: root_path)
  end
  
  def likes
    @user = User.find(params[:id])
    @pagy, @likings = pagy(@user.likings)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password) # name, email, passwordを許可
  end
  
  def correct_user
    @user = current_user.users.find_by(id: params[:id])
    unless @user
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user # 現在ログインしているユーザを取得するメソッド
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in? # ユーザがログインしていればtrue、していなければfalseを返すメソッド
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper # Gravatarの呼び出し
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/cabinets/_cabinets.html.erb
<% if cabinets.any? %> 
  <% cabinets.each do |cabinet| %>
    <div>
      <%= link_to cabinet.title_cabinet + "内閣", cabinet_path(current_user) %>
    </div>
    <div>
      <%= render "favorites/like_button", cabinet: cabinet %>
    </div>
  <% end %>
<% end %>

app/views/cabinets/_form.html.erb
<%= form_with(model: cabinet) do |f| %>
  <% if cabinet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cabinet.errors.count, "組閣できませんでした") %></h2>

      <ul>
        <% cabinet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p class="text-center">タイトル</p>
  <h2 class="text-center"><%= f.text_field :title_cabinet %>内閣</h2>
  
  <table class="table">
    <tr>
      <th>職名</th>
      <th>氏名</th>
    </tr>
    <tr>
      <td><%= f.label :prime_minister_name, "内閣総理大臣" %></td>
      <td><%= f.text_field :prime_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :chief_cabinet_secretary_name, "内閣官房長官" %></td>
      <td><%= f.text_field :chief_cabinet_secretary_name %></td>
    </tr>
    <tr>
      <td><%= f.label :finance_minister_name, "財務大臣" %></td>
      <td><%= f.text_field :finance_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :comprehensive_minister_name, "総務大臣" %></td>
      <td><%= f.text_field :comprehensive_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :economy_minister_name, "経済産業大臣" %></td>
      <td><%= f.text_field :economy_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :welfare_minister_name, "厚生労働大臣" %></td>
      <td><%= f.text_field :welfare_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :education_minister_name, "文部科学大臣" %></td>
      <td><%= f.text_field :education_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :diplomacy_minister_name, "外務大臣" %></td>
      <td><%= f.text_field :diplomacy_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :defense_minister_name, "防衛大臣" %></td>
      <td><%= f.text_field :defense_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :agriculture_minister_name, "農林水産大臣" %></td>
      <td><%= f.text_field :agriculture_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :traffic_minister_name, "国土交通大臣" %></td>
      <td><%= f.text_field :traffic_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :law_minister_name, "法務大臣" %></td>
      <td><%= f.text_field :law_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :green_minister_name, "環境大臣" %></td>
      <td><%= f.text_field :green_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :digital_minister_name, "デジタル大臣" %></td>
      <td><%= f.text_field :digital_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :reconstruction_minister_name, "復興大臣" %></td>
      <td><%= f.text_field :reconstruction_minister_name %></td>
    </tr>
    <tr>
      <td><%= f.label :public_security_minister_name, "国家公安委員長" %></td>
      <td><%= f.text_field :public_security_minister_name %></td>
    </tr>
  </table>
                  
    <%= f.submit "組閣", class: "btn btn-sm", style: "background-color: gray;" %>
<% end %>

app/views/cabinets/edit.html.erb
<h1 class="text-center"><%= @cabinet.title_cabinet %>内閣</h1>

<%= render "form", cabinet: @cabinet %>

<%= link_to '一覧に戻る', cabinets_path %>

app/views/cabinets/index.html.erb
<h1><%= current_user.name %>さんの内閣一覧</h1>

  <% @cabinets.each do |cabinet| %>
  <div>
    <%= link_to cabinet.title_cabinet + "内閣" , cabinet %>
  </div>
    <% if current_user == cabinet.user %>
    <div>
      <%= link_to "Delete", cabinet, method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'btn btn-danger btn-sm' %>
    </div>
    <% end %>
  <% end %>

app/views/cabinets/new.html.erb
<%= render "form", cabinet: @cabinet %>

<%= link_to "ユーザーページに戻る", root_path %>

app/views/cabinets/show.html.erb
<h1 class="text-center"><%= @cabinet.title_cabinet %>内閣</h1>

  <table class="table">
    <tr>
      <th>職名</th>
      <th>氏名</th>
    </tr>
    <tr>
      <td>内閣総理大臣</td>
      <td><%= @cabinet.prime_minister_name %></td>
    </tr>
    <tr>
      <td>内閣官房長官</td>
      <td><%= @cabinet.chief_cabinet_secretary_name %></td>
    </tr>
    <tr>
      <td>財務大臣</td>
      <td><%= @cabinet.finance_minister_name %></td>
    </tr>
    <tr>
      <td>総務大臣</td>
      <td><%= @cabinet.comprehensive_minister_name %></td>
    </tr>
    <tr>
      <td>経済産業大臣</td>
      <td><%= @cabinet.economy_minister_name %></td>
    </tr>
    <tr>
      <td>厚生労働大臣</td>
      <td><%= @cabinet.welfare_minister_name %></td>
    </tr>
    <tr>
      <td>文部科学大臣</td>
      <td><%= @cabinet.education_minister_name %></td>
    </tr>
    <tr>
      <td>外務大臣</td>
      <td><%= @cabinet.diplomacy_minister_name %></td>
    </tr>
    <tr>
      <td>防衛大臣</td>
      <td><%= @cabinet.defense_minister_name %></td>
    </tr>
    <tr>
      <td>農林水産大臣</td>
      <td><%= @cabinet.agriculture_minister_name %></td>
    </tr>
    <tr>
      <td>国土交通大臣</td>
      <td><%= @cabinet.traffic_minister_name %></td>
    </tr>
    <tr>
      <td>法務大臣</td>
      <td><%= @cabinet.law_minister_name %></td>
    </tr>
    <tr>
      <td>環境大臣</td>
      <td><%= @cabinet.green_minister_name %></td>
    </tr>
    <tr>
      <td>デジタル大臣</td>
      <td><%= @cabinet.digital_minister_name %></td>
    </tr>
    <tr>
      <td>復興大臣</td>
      <td><%= @cabinet.reconstruction_minister_name %></td>
    </tr>
    <tr>
      <td>国家公安委員長</td>
      <td><%= @cabinet.public_security_minister_name %></td>
    </tr>
  </table>
  
  <%= link_to "編集する", edit_cabinet_path(@cabinet), class: 'btn btn-sm', style: "background-color: gray;" %>

app/views/cabinets/update.html.erb
<h1>Cabinets#update</h1>
<p>Find me in app/views/cabinets/update.html.erb</p>

app/views/favorites/_like_button.html.erb
  <% if current_user.liking?(cabinet) %> <!--もし、ログイン中のユーザがお気に入り登録したら、-->
    <%= form_with(model: current_user.favorites.find_by(cabinet_id: cabinet.id), method: :delete) do |f| %> <!--お気に入り解除できるものを取り出す-->
      <%= hidden_field_tag :cabinet_id, cabinet.id %> <!--<input type="hidden" name="cabinet_id" value="cabinet.id">の生成 -->
      <%= f.submit 'Unlike', class: 'btn btn-success btn-sm text-light' %> <!--Unlikeボタンを表示する-->
    <% end %>
  <% else %> <!--違ければ-->
    <%= form_with(model: current_user.favorites.build) do |f| %> <!--お気に入り登録中のCabinetではなかったら、-->
      <%= hidden_field_tag :cabinet_id, cabinet.id %> <!--<input type="hidden" name="cabinet_id" value="cabinet.id">の生成 -->
      <%= f.submit 'Like', class: 'btn btn-warning btn-sm text-light' %> <!--Likeボタンを表示する-->
    <% end %>
  <% end %>

<!---->

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #eb6101;">
    <div class="container-fluid ps-5 pe-5">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="#" class="nav-link">HOME</a></li>
        <li class="nav-item"><a href="#" class="nav-link">運営者情報</a></li>
        <li class="nav-item"><a href="#" class="nav-link">お問い合わせ</a></li>
      </ul>
    </div>
  </nav>
</footer>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #eb6101;">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">My内閣</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
          <div class="btn-group">
            <ul class="navbar-nav">
              <li class="ms-3"><%= link_to '組閣', new_cabinet_path, class: 'nav-link' %></li>
            </ul>
            <button type="button" class="btn dropdown-toggle" style="background-color: #eb6101;" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li class="dropdown-item"><%= link_to '組閣', new_cabinet_path, class: 'nav-link' %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to "作成した内閣一覧", cabinets_path, class: "nav-link" %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to "お気に入りの内閣一覧", likes_user_path(current_user), class: "nav-link" %></li>
              <li class="dropdown-divider"></li>              
              <li class="dropdown-item"><%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %></li>
            </ul>
          </div>
        <% else %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "ユーザー登録", signup_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link" %></li>
        </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
    <title>My内閣</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false" style="min-height: 100vh; position: relative; padding-bottom: 120px; box-sizing: border-box;">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
      
  </body>
</html>

app/views/toppages/index.html.erb
  <% @cabinets.each do |cabinet| %>
    <div>
      <%= link_to cabinet.title_cabinet + "内閣", cabinet %>
    </div>
    <% if logged_in? %>
      <div>
        <%= render "favorites/like_button", cabinet: cabinet %>
      </div>
    <% end %>
  <% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="mb-3 d-flex">
        <img class="rounded me-2" src="<%= gravatar_url(user, { size: 64 }) %>" alt="">
        <div>
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user), class: "text-decoration-none" %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/users/likes.html.erb
<%= render "cabinets/cabinets", cabinets: @likings %>

app/views/users/new.html.erb
<%= form_with(model: @user) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
<% end %>
  
<div class="text-center">
  <h1>ユーザー登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>

      <div class="mb-3">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'Eメール' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <%= f.submit 'ユーザー登録', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>